version: '3.8'

services:
  app:
    build: .
    container_name: setorwa-app
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./sessions:/app/sessions
      - ./public/uploads:/app/public/uploads
    environment:
      - PORT=3001
      - TZ=Asia/Jakarta
      - NODE_ENV=production
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
